name: Cypress Tests using Cypress Docker Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  chrome:
    runs-on: ubuntu-latest
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2

      - uses: actions/checkout@v2

      - name: Install
        run: pnpm install --frozen-lockfile

      - uses: cypress-io/github-action@v4
        with:
          start: pnpm dev
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
          browser: chrome
